# Role definition
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: amirrshams
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "deployments", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
  
---
# Role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: amirrshams-binding
  namespace: default
subjects:
- kind: User
  name: amirrshams 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: amirrshams
  apiGroup: rbac.authorization.k8s.io

